### ISSUE TITLE
Reading DS1202CA files  failed

### ISSUE THREAD

**Issue by benvanloock** [scottprahl/RigolWFM#15]
Attempted to convert a WFM file of DS1202CA to CSV but it failed :
$ python --version
Python 3.8.5

$ wfmconvert C csv NewFile6.wfm
Traceback (most recent call last):
  File "/home/ben/Downloads/wfm/bin/wfmconvert", line 8, in <module>
    sys.exit(main())
  File "/home/ben/Downloads/wfm/lib/python3.8/site-packages/RigolWFM/wfmconvert.py", line 125, in main
    scope_data = rigol.Wfm.from_file(filename, args.model)
  File "/home/ben/Downloads/wfm/lib/python3.8/site-packages/RigolWFM/wfm.py", line 180, in from_file
    ch = RigolWFM.channel.Channel(w, ch_number, pname, enabled_channels)
  File "/home/ben/Downloads/wfm/lib/python3.8/site-packages/RigolWFM/channel.py", line 132, in __init__
    self.seconds_per_point = w.header.seconds_per_point
  File "/home/ben/Downloads/wfm/lib/python3.8/site-packages/RigolWFM/wfm1000c.py", line 203, in header
    self._m_header = self._root.Header(self._io, self, self._root)
  File "/home/ben/Downloads/wfm/lib/python3.8/site-packages/RigolWFM/wfm1000c.py", line 59, in __init__
    self._read()
  File "/home/ben/Downloads/wfm/lib/python3.8/site-packages/RigolWFM/wfm1000c.py", line 62, in _read
    self.magic = self._io.ensure_fixed_contents(b"\xA5\xA5\x00\x00")
  File "/home/ben/Downloads/wfm/lib/python3.8/site-packages/kaitaistruct.py", line 323, in ensure_fixed_contents
    raise Exception(
Exception: unexpected fixed contents: got b'\xa1\xa5\x00\x00', was waiting for b'\xa5\xa5\x00\x00'

The wfm file is  attached.

[NewFile6.wfm.gz](https://github.com/scottprahl/RigolWFM/files/5976193/NewFile6.wfm.gz)

**Comment by scottprahl** [comment]
Thanks for the test file.  This is the first 1000C version file that the code has been tested against.

Several minor changes were needed to get things working.  I have uploaded these to github.  

I am not sure if everything is working exactly as it should.  Everything looks reasonable, but it would be nice to verify that voltages and times are exactly right.

Please test the latest version on github.  If you find errors, then please upload both the `.wfm` files and `.csv` or `.bmp` files so I can figure out what is going wrong.

If this version works well enough, then I will just spin a new release.  Just let me know.

**Comment by benvanloock** [comment]
Hi Scott,

Already many thanks for your effort!

I did a first conversion of two other files. As this is something of my son studying physics he'll check the output CSV files later on. And then I'll let you know if your files work correctly.


⁣Cheers, Ben​

**Comment by benvanloock** [comment]
I converted now 19 files to CSV. They were checked and it seems voltages and timing are as expected ! Cool !
You can spin a new release !  ;)
Many thanks !

Cheers, Ben

**Comment by scottprahl** [comment]
Great news!  I released version 0.7.  Thanks for your contribution.
