### ISSUE TITLE
DS1202ZE

### ISSUE THREAD

**Issue by JoetVer** [scottprahl/RigolWFM#22]
Hi Scott, Just wondering when you may have time to include the DS1202ZE?

**Comment by scottprahl** [comment]
I don't have much time, but the files you sent seemed to parse ok. 

`RigolWFM/wfmconvert.py Z info wfm/DS1202Z-2.wfm`

What is the problem?

**Comment by JoetVer** [comment]
[Rigol1202Z.zip](https://github.com/scottprahl/RigolWFM/files/7208176/Rigol1202Z.zip)

Scott, I have added a few more files for two cases, one channel used and two channels used. For the single input case the code interpreted the data file to have three channels, Ch1 (1mV/div + offset -2.5mV), Ch3(-2nV/div+offset -2nV) and Ch4(-2nV/div+offset -2nV). Also, there is some sort of transient visible at the end of the python plot, that is not in the CSV or image file. I think I observed that on occasional files when processing files from the DS1204B as wel
![File1 Ch3 plot from python](https://user-images.githubusercontent.com/87792651/134296108-8e71d612-2d64-4f77-9176-56c0901b4839.png)
![File1 Ch4 plot from python](https://user-images.githubusercontent.com/87792651/134296111-11fc2a4b-bff8-49bc-87c6-6acf87417441.png)
![File1 Ch1 plot from python](https://user-images.githubusercontent.com/87792651/134296112-e7d4266b-c77f-4836-81b7-328735502630.png)
l.

**Comment by Kosi81** [comment]
mhm have an issue with a File from DS1202ZE

wfmconvert.py Z info wfm/DS1202Z-2.wfm is working but says it is a File Model   = wfm1000z

But when trying to convert i get: 

Traceback (most recent call last):
  File "C:\wfm\example.py", line 7, in <module>
    w = rigol.Wfm.from_file(filename, scope)
  File "C:\Users\marti\AppData\Roaming\Python\Python310\site-packages\RigolWFM\wfm.py", line 209, in from_file
    ch = RigolWFM.channel.Channel(w, ch_number, pname, selected)
  File "C:\Users\marti\AppData\Roaming\Python\Python310\site-packages\RigolWFM\channel.py", line 115, in __init__
    self.seconds_per_point = w.header.seconds_per_point
  File "C:\Users\marti\AppData\Roaming\Python\Python310\site-packages\RigolWFM\wfm1000e.py", line 384, in header
    self._m_header = Wfm1000e.Header(self._io, self, self._root)
  File "C:\Users\marti\AppData\Roaming\Python\Python310\site-packages\RigolWFM\wfm1000e.py", line 205, in __init__
    self._read()
  File "C:\Users\marti\AppData\Roaming\Python\Python310\site-packages\RigolWFM\wfm1000e.py", line 210, in _read
    raise kaitaistruct.ValidationNotEqualError(b"\xA5\xA5\x00\x00", self.magic, self._io, u"/types/header/seq/0")
kaitaistruct.ValidationNotEqualError: /types/header/seq/0: at pos 4: validation failed: not equal, expected b'\xa5\xa5\x00\x00', but got b'\x01\xff\xff\xff'


FIle: [NewGa.wfm](https://www.kousek.at/NewGa.wfm)

**Comment by strong-hub** [comment]
> [Rigol1202Z.zip](https://github.com/scottprahl/RigolWFM/files/7208176/Rigol1202Z.zip)
> 
> Scott, I have added a few more files for two cases, one channel used and two channels used. For the single input case the code interpreted the data file to have three channels, Ch1 (1mV/div + offset -2.5mV), Ch3(-2nV/div+offset -2nV) and Ch4(-2nV/div+offset -2nV). Also, there is some sort of transient visible at the end of the python plot, that is not in the CSV or image file. I think I observed that on occasional files when processing files from the DS1204B as wel ![File1 Ch3 plot from python](https://user-images.githubusercontent.com/87792651/134296108-8e71d612-2d64-4f77-9176-56c0901b4839.png) ![File1 Ch4 plot from python](https://user-images.githubusercontent.com/87792651/134296111-11fc2a4b-bff8-49bc-87c6-6acf87417441.png) ![File1 Ch1 plot from python](https://user-images.githubusercontent.com/87792651/134296112-e7d4266b-c77f-4836-81b7-328735502630.png) l.

same issue

**Comment by scottprahl** [comment]
this seems to be fixed now.
