### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by beta-tester** [scottprahl/RigolWFM#24]
hi,
i wanted to try your RigolWFM on my Raspberry Pi (RPi4 + RasPi OS Bullseye) but i can't get it running:
i did: 
```
pip install --user RigolWFM
```

and then i tried 
```
import matplotlib.pyplot as plt
import RigolWFM.wfm as rigol

filename = 'example.wfm'
scope = 'DS1000E'

w = rigol.Wfm.from_file(filename, scope)
w.plot()
plt.show()
```

but i get an error:
```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "/home/pi/Documents/test_rigol_wfm.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
```

i also don't find the commandline tool `wfmconvert`

**Comment by scottprahl** [comment]
Sorry, I don't have a Raspberry Pi to test with.  Something is wrong because you are unable to even load `matplotlib`.  If you figure out how to fix this, let me know and perhaps I can modify the packaging to accommodate the RPi platform.

**Comment by beta-tester** [comment]
i think there was something wrong with the `matplotlib` installation that came with `RigolWFM` package,
because already the following example gave that error:
```
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 5, 0.1)
y = np.sin(x)
plt.plot(x, y)
```

but i coukd not find any broken requirements:
```
$ pip check
No broken requirements found.
```


i uninstaled `RigolWFM` and all packages that were installed with `RigolWFM`.
```
pip uninstall RigolWFM
pip uninstall cycler fonttools kaitaistruct kiwisolver matplotlib packaging pyparsing python-dateutil
pip cache purge
```


then i manually installed `matplotlib`:
```
$ pip install --user matplotlib
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting matplotlib
  Downloading matplotlib-3.5.1.tar.gz (35.3 MB)
     |████████████████████████████████| 35.3 MB 54 kB/s 
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3/dist-packages (from matplotlib) (0.10.0)
Collecting fonttools>=4.22.0
  Downloading https://www.piwheels.org/simple/fonttools/fonttools-4.28.3-cp39-cp39-linux_armv7l.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 987 kB/s 
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/lib/python3/dist-packages (from matplotlib) (1.3.1)
Requirement already satisfied: numpy>=1.17 in /usr/lib/python3/dist-packages (from matplotlib) (1.19.5)
Collecting packaging>=20.0
  Using cached https://www.piwheels.org/simple/packaging/packaging-21.3-py3-none-any.whl (40 kB)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib) (8.1.2)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3/dist-packages (from matplotlib) (2.8.1)
Building wheels for collected packages: matplotlib
  Building wheel for matplotlib (setup.py) ... done
  Created wheel for matplotlib: filename=matplotlib-3.5.1-cp39-cp39-linux_armv7l.whl size=10741161 sha256=6380a1cbb1de213bd3bb490b030ee704c2fe5370cce5b6ce5eb01d4a05c4d816
  Stored in directory: /home/pi/.cache/pip/wheels/38/64/b5/a974d9c8164e4948decd1dc047d12445c22f6bae0f0cfe16c7
Successfully built matplotlib
Installing collected packages: packaging, fonttools, matplotlib
Successfully installed fonttools-4.28.3 matplotlib-3.5.1 packaging-21.3
```


and then `RigolWFM`:
```
$ pip install --user RigolWFM
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting RigolWFM
  Downloading https://www.piwheels.org/simple/rigolwfm/RigolWFM-0.9.4-py3-none-any.whl (32 kB)
Collecting kaitaistruct
  Downloading https://www.piwheels.org/simple/kaitaistruct/kaitaistruct-0.9-py2.py3-none-any.whl (6.9 kB)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from RigolWFM) (1.19.5)
Requirement already satisfied: matplotlib in ./.local/lib/python3.9/site-packages (from RigolWFM) (3.5.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from RigolWFM) (2.25.1)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3/dist-packages (from matplotlib->RigolWFM) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib->RigolWFM) (8.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3/dist-packages (from matplotlib->RigolWFM) (2.8.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.local/lib/python3.9/site-packages (from matplotlib->RigolWFM) (4.28.3)
Requirement already satisfied: packaging>=20.0 in ./.local/lib/python3.9/site-packages (from matplotlib->RigolWFM) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib->RigolWFM) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/lib/python3/dist-packages (from matplotlib->RigolWFM) (1.3.1)
Installing collected packages: kaitaistruct, RigolWFM
Successfully installed RigolWFM-0.9.4 kaitaistruct-0.9
```

now i can run `wfmconvert` successfully.
but i have no idea, why it is now working and why `matplotlib` was broken before.

now i can convert the WFM of my DS1042C to a proper csv
(the csv that the DS1042C generates has a huge loss in time resolution - useless to work with)

csv generated by DS1042C:
```
X,CH1
Second,Volt,
-5.11e-03,2.00e-02
-5.11e-03,2.00e-02
...
-1.00e-07,-2.00e-02
-4.97e-08,-4.00e-02
-3.80e-10,-2.00e-02
4.99e-08,0.00e+00
1.00e-07,-2.00e-02
1.50e-07,-2.00e-02
2.00e-07,0.00e+00
2.50e-07,7.60e-01
3.00e-07,2.32e+00
3.50e-07,3.02e+00
4.00e-07,3.40e+00
4.49e-07,3.54e+00
5.00e-07,2.98e+00
5.50e-07,1.38e+00
6.00e-07,6.40e-01
6.50e-07,3.20e-01
7.00e-07,1.80e-01
7.50e-07,4.00e-02
8.00e-07,4.00e-02
8.50e-07,2.00e-02
9.00e-07,2.00e-02
...
```
csv converted from wfm file by  wfmconvert :
```
X,CH 1,Start,Increment
ms,mV,-6.000000e-03,1.000000e-05
-5.107200,60.00
-5.107150,60.00
...
-0.000140,20.00
-0.000090,20.00
-0.000040,0.00
0.000010,20.00
0.000060,40.00
0.000110,20.00
0.000160,20.00
0.000210,40.00
0.000260,800.00
0.000310,2360.00
0.000360,3060.00
0.000410,3440.00
0.000460,3580.00
0.000510,3020.00
0.000560,1420.00
0.000610,680.00
0.000660,360.00
0.000710,220.00
0.000760,80.00
0.000810,80.00
0.000860,60.00
...
```
anyhow thank you for your work.
