### ISSUE TITLE
DS1074Z Plus Logic analyzer channels are not recognized

### ISSUE THREAD

**Issue by AlejandroBizzotto** [scottprahl/RigolWFM#25]
if I try just one LA channel I get a division by zero error:

python .\rigol_plt.py
Traceback (most recent call last):
  File "C:\Users\jano\workfolder\code\memosens\rigol_plt.py", line 7, in <module>
    w = rigol.Wfm.from_file(filename, scope)
  File "C:\Users\jano\AppData\Roaming\Python\Python310\site-packages\RigolWFM\wfm.py", line 209, in from_file
    ch = RigolWFM.channel.Channel(w, ch_number, pname, selected)
  File "C:\Users\jano\AppData\Roaming\Python\Python310\site-packages\RigolWFM\channel.py", line 162, in __init__
    self.ds1000z(w, channel_number)
  File "C:\Users\jano\AppData\Roaming\Python\Python310\site-packages\RigolWFM\channel.py", line 294, in ds1000z
    self.points = w.header.points
  File "C:\Users\jano\AppData\Roaming\Python\Python310\site-packages\RigolWFM\wfm1000z.py", line 274, in points
    self._m_points = self.memory_depth // self.stride
ZeroDivisionError: integer division or modulo by zero

rigol_plt.py contains:

```
import matplotlib.pyplot as plt
import RigolWFM.wfm as rigol

filename = 'test1.wfm'
scope = 'DS1074Z'

w = rigol.Wfm.from_file(filename, scope)
w.plot()
plt.show()
```

if along with the LA I turn on CH1, the picture has blocks which are not correct:
![image](https://user-images.githubusercontent.com/102295653/159904670-a558e74b-5725-46d5-a487-9a33b70c44cc.png)
If I zoom in:
![image](https://user-images.githubusercontent.com/102295653/159904987-d8c41aa9-66ab-4800-863e-090278ccd663.png)

the pictures in the scope:
![test3](https://user-images.githubusercontent.com/102295653/159905202-16fcc49f-67f6-4169-9b60-d6d28a4a706b.png)
![test31](https://user-images.githubusercontent.com/102295653/159905240-6b025ed0-942a-4875-b179-b010c359be8f.png)

I also tried wfmconver.exe, it stays forever doing nothing.
the files:
[D.zip](https://github.com/scottprahl/RigolWFM/files/8340979/D.zip)

firmware on the scope is 00.04.05.SP2, there is nothing newer than this one on Rigol's website.

**Comment by scottprahl** [comment]
Nice bug report.  Unfortunately, the logic analyzer is completely undocumented and unsupported.

1) The Logic Analyzer functions are not supported and have never been tested
2) I didn't have a Z series test file with no channels enabled and therefore the division by zero never arose 
3) I just looked and I have no information about how the logic analyzer data is stored or interpreted. For example, I don't see *any* information in the header that indicates that digital channel 6 was used.

**Comment by AlejandroBizzotto** [comment]
inside the attached D.zip file, test1.wfm has only digital 6 enabled, test3.wfm has digital 6 and analog 1. the digital content should be the same in both, the analog input was not connected (not even the probe).
I only have access to the scope at work (I have the same series oscilloscope at home, but without LA). If there is any other data I can gather to help analyzing this, please let me know.

**Comment by scottprahl** [comment]
I see.  Thanks for clarification about what was saved.

The problem is that I do not know where in the file header to find any information about digital signals.  Most specifically which signals have been saved.

The digital data is stored in 2 byte arrays.  One for D7-D0 and the other for D15-D8.  However, for example, `test1.wfm` has a bunch of 0x40 values (which is not 2^6 as one might expect for digital 6).  So it is also not obvious how to interpret the bytes that are saved.  If we could do that, then we could just discard all the arrays that are identically zeros as not having been saved.

You could help by using going to the [kaitai struct IDE](https://ide.kaitai.io/) and adding [wfm1000z.ksy](https://github.com/scottprahl/RigolWFM/blob/master/ksy/wfm1000z.ksy) along with the `.wfm` that you are interested in decoding.  I don't have the time (or equipment) to reverse engineer this stuff.

Finally, you could also contact Rigol Technical Support and ask them to tell you how to interpret the MSO files.

**Comment by brainstorm** [comment]
As you might have noticed on #27, I'm trying to figure out that WFM and your comment piked my interest:

> The digital data is stored in 2 byte arrays. One for D7-D0 and the other for D15-D8. However, for example, test1.wfm has a bunch of 0x40 values (which is not 2^6 as one might expect for digital 6). So it is also not obvious how to interpret the bytes that are saved. If we could do that, then we could just discard all the arrays that are identically zeros as not having been saved.

Where did you see that? Here's what I see when I have all digital channels enabled (`test0.wfm`) and then all of them disabled except D0 and D1:

<img width="1177" alt="Screen Shot 2023-01-02 at 9 20 41 pm" src="https://user-images.githubusercontent.com/175587/210218664-a82903d9-72ee-438b-b89b-703b4f2ad472.png">

Actual waveform data seems to be encoded later?

<img width="1180" alt="Screen Shot 2023-01-02 at 9 51 36 pm" src="https://user-images.githubusercontent.com/175587/210221860-2807ff0f-0d6f-4724-8414-11fc7bdadbf1.png">

<img width="1175" alt="Screen Shot 2023-01-02 at 9 24 29 pm" src="https://user-images.githubusercontent.com/175587/210219046-3e064134-1110-4562-8e7a-d475406cc153.png">

@scottprahl, I know your time is limited to dedicate to this particular reversing, but since you've seem a few of those, maybe you can identify patterns that you've seen before and therefore I can fully decode and put it together in Kaitai (as soon as I understand it)?

**Comment by scottprahl** [comment]
Well, I just added support for this.
